/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-04-24 03:24:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1555569358770L));
    _jspx_dependants.put("jar:file:/C:/workspaceProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jsphomme/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspaceProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jsphomme/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>상품 등록</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" \r\n");
      out.write("\tsrc=\"/jsphomme/resources/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function goInsert() {\r\n");
      out.write("\t\r\n");
      out.write("\tvar fileObj = document.getElementById(\"file\");\r\n");
      out.write("\tvar nameObj = document.getElementById(\"name\");\r\n");
      out.write("\tvar priceObj = document.getElementById(\"price\");\r\n");
      out.write("\tvar quantityObj = document.getElementById(\"quantity\");\r\n");
      out.write("\tvar formTagObj = document.getElementById(\"formTag\");\r\n");
      out.write("\t\r\n");
      out.write("\tif (fileObj.value == \"\") {\r\n");
      out.write("\t\talert(\"파일을 추가해주세요!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif (nameObj.value == \"\") {\r\n");
      out.write("\t\talert(\"상품 이름을 입력해주세요!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif (priceObj.value == \"\") {\r\n");
      out.write("\t\talert(\"가격을 입력해주세요!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif (quantityObj.value == \"\") {\r\n");
      out.write("\t\talert(\"입고 물량을 입력해주세요!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tformTagObj.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function goBack() {\r\n");
      out.write("\tlocation.href = \"/jsphomme/product/list.do\"\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t\r\n");
      out.write("\t.detailView {\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t\twidth: 1200px;\r\n");
      out.write("\t\toverflow: hidden;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.explanation {\r\n");
      out.write("\t\tfloat: right;\r\n");
      out.write("\t\twidth: 600px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.detail > ul  {\r\n");
      out.write("\t\tlist-style-type: none;\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\timg {\r\n");
      out.write("\t\twidth: 500px;\r\n");
      out.write("\t\theight: 500px;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttextarea {\r\n");
      out.write("\t\tresize: none;\r\n");
      out.write("\t\twidth: 1190px;\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t\tmargin-top: 50px;\r\n");
      out.write("\t\theight: 400px;\r\n");
      out.write("\t\tborder-radius: 7px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.explanation > td{\r\n");
      out.write("\t\twidth: 150px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/headerAfterLogin.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<h1>상품 등록</h1>\r\n");
      out.write("\t<div class=\"detailView\">\r\n");
      out.write("\t\t<form action=\"./insert.do\" id=\"formTag\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<table class=\"explanation\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\"><input type=\"file\" id=\"file\" name=\"file\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>상품 이름</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"name\" name=\"name\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>가격</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"number\" id=\"price\" name=\"price\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>입고 물량</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"number\" id=\"quantity\" name=\"quantity\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"reset\" value=\"취소\"></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"button\" value=\"등록\" onclick=\"goInsert();\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<div style=\"clear: both;\">\t\t\t\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"뒤로가기\" onclick=\"goBack();\">\r\n");
      out.write("\t\t\t\t<textarea name=\"detail\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/tail.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
