/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-04-18 07:24:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class headerAdminAfterLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1555569358770L));
    _jspx_dependants.put("jar:file:/C:/workspaceProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jsphomme/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t#headerContainer {\r\n");
      out.write("\t\twidth: 1904px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.shopName {\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tmargin-left: 50px;\r\n");
      out.write("\t\tmargin-bottom: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.shopName input  {\r\n");
      out.write("\t\tbackground-color: #636363; \r\n");
      out.write("\t\ttext-align: center; \r\n");
      out.write("\t\twidth: 250px; \r\n");
      out.write("\t\theight: 40px;\r\n");
      out.write("\t\tcolor: #FFFFFF;\r\n");
      out.write("\t\tfont-size: 23px; \r\n");
      out.write("\t\tfont-weight: bolder;\r\n");
      out.write("\t\tfont-style: normal;\r\n");
      out.write("\t\tfont-family: \"Lucida Console\", Monaco, monospace;\r\n");
      out.write("\t\tborder-radius: 7px;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.fncButton {\r\n");
      out.write("\t\tfloat: right;\r\n");
      out.write("\t\tmargin-top: 13px;\r\n");
      out.write("\t\tmargin-right: 50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.headerLine {\r\n");
      out.write("\t\tclear: both;\r\n");
      out.write("\t\tmargin-top: 50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.headerLine hr {\r\n");
      out.write("\t\tborder: solid 1.5px #ABABAB;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.productRegiBtn {\r\n");
      out.write("\t\tbackground-color: #DBDBDB; \r\n");
      out.write("\t\ttext-align: center; \r\n");
      out.write("\t\twidth:70px; \r\n");
      out.write("\t\theight: 25px;\r\n");
      out.write("\t\tcolor: #939393;\r\n");
      out.write("\t\tfont-size: 11px; \r\n");
      out.write("\t\tfont-weight: bolder;\r\n");
      out.write("\t\tfont-style: normal;\r\n");
      out.write("\t\tfont-family: \"Lucida Console\", Monaco, monospace;\r\n");
      out.write("\t\tborder-radius: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.myPageBtn {\r\n");
      out.write("\t\tbackground-color: #DBDBDB; \r\n");
      out.write("\t\ttext-align: center; \r\n");
      out.write("\t\twidth:70px; \r\n");
      out.write("\t\theight: 25px;\r\n");
      out.write("\t\tcolor: #939393;\r\n");
      out.write("\t\tfont-size: 11px; \r\n");
      out.write("\t\tfont-weight: bolder;\r\n");
      out.write("\t\tfont-style: normal;\r\n");
      out.write("\t\tfont-family: \"Lucida Console\", Monaco, monospace;\r\n");
      out.write("\t\tborder-radius: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.memberListBtn {\r\n");
      out.write("\t\tbackground-color: #DBDBDB; \r\n");
      out.write("\t\ttext-align: center; \r\n");
      out.write("\t\twidth:70px; \r\n");
      out.write("\t\theight: 25px;\r\n");
      out.write("\t\tcolor: #939393;\r\n");
      out.write("\t\tfont-size: 11px; \r\n");
      out.write("\t\tfont-weight: bolder;\r\n");
      out.write("\t\tfont-style: normal;\r\n");
      out.write("\t\tfont-family: \"Lucida Console\", Monaco, monospace;\r\n");
      out.write("\t\tborder-radius: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.purchaseListBtn {\r\n");
      out.write("\t\tbackground-color: #636363;\r\n");
      out.write("\t\ttext-align: center; \r\n");
      out.write("\t\twidth:70px; \r\n");
      out.write("\t\theight: 25px;\r\n");
      out.write("\t\tcolor: #FFFFFF;\r\n");
      out.write("\t\tfont-size: 11px; \r\n");
      out.write("\t\tfont-weight: bolder;\r\n");
      out.write("\t\tfont-style: normal;\r\n");
      out.write("\t\tfont-family: \"Lucida Console\", Monaco, monospace;\r\n");
      out.write("\t\tborder-radius: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.logoutBtn {\r\n");
      out.write("\t\tbackground-color: #636363;\r\n");
      out.write("\t\ttext-align: center; \r\n");
      out.write("\t\twidth:70px; \r\n");
      out.write("\t\theight: 25px;\r\n");
      out.write("\t\tcolor: #FFFFFF;\r\n");
      out.write("\t\tfont-size: 11px; \r\n");
      out.write("\t\tfont-weight: bolder;\r\n");
      out.write("\t\tfont-style: normal;\r\n");
      out.write("\t\tfont-family: \"Lucida Console\", Monaco, monospace;\r\n");
      out.write("\t\tborder-radius: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<title>JSP Homme</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function productRegiFnc() {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function myPageFnc() {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function memberListFnc() {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function purchaseListFnc() {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function logoutFnc() {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"headerContainer\" >   \r\n");
      out.write("\r\n");
      out.write("\t<div class=\"shopName\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"JSP Homme\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!-- 관리자가 로그인 후 보일 버튼-->\r\n");
      out.write("\t\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!-- 일반 회원 로그인 후 보일 버튼-->\r\n");
      out.write("\t\r\n");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"headerLine\">\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/common/headerAdminAfterLogin.jsp(159,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberVo.authority == '0'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\t\r\n");
        out.write("\t\r\n");
        out.write("\t<div class=\"fncButton\">\t\r\n");
        out.write("\t\t<span> ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session.memberVo.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write(" </span>\r\n");
        out.write("\t\t<input class=\"productRegiBtn\" type=\"button\" value=\"상품등록\" onclick=\"productRegiFnc();\">\r\n");
        out.write("\t\t<input class=\"myPageBtn\" type=\"button\" value=\"마이페이지\" onclick=\"myPageFnc();\">\r\n");
        out.write("\t\t<input class=\"memberListBtn\" type=\"button\" value=\"회원목록\" onclick=\"memberListFnc();\">\r\n");
        out.write("\t\t<input class=\"purchaseListBtn\" type=\"button\" value=\"구매목록\" onclick=\"purchaseListFnc();\">\r\n");
        out.write("\t\t<input class=\"logoutBtn\" type=\"button\" value=\"로그아웃\" onclick=\"logoutFnc();\">\r\n");
        out.write("\t</div>\r\n");
        out.write("\r\n");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/views/common/headerAdminAfterLogin.jsp(174,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberVo.authority == '일반'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\t\r\n");
        out.write("\t<div class=\"fncButton\">\t\r\n");
        out.write("\t\t<span> ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session.memberVo.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write(" </span>\r\n");
        out.write("\t\t<input class=\"myPageBtn\" type=\"button\" value=\"마이페이지\" onclick=\"myPageFnc();\">\r\n");
        out.write("\t\t<input class=\"purchaseListBtn\" type=\"button\" value=\"구매목록\" onclick=\"purchaseListFnc();\">\r\n");
        out.write("\t\t<input class=\"logoutBtn\" type=\"button\" value=\"로그아웃\"  onclick=\"logoutFnc();\" >\r\n");
        out.write("\t</div> n  \r\n");
        out.write("\t\r\n");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
