/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-04-17 08:57:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class headerAdminAfterLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t#headerContainer {\r\n");
      out.write("\t\twidth: 1904px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.shopName {\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tmargin-left: 50px;\r\n");
      out.write("\t\tmargin-bottom: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.shopName input  {\r\n");
      out.write("\t\tbackground-color: #636363; \r\n");
      out.write("\t\ttext-align: center; \r\n");
      out.write("\t\twidth: 250px; \r\n");
      out.write("\t\theight: 40px;\r\n");
      out.write("\t\tcolor: #FFFFFF;\r\n");
      out.write("\t\tfont-size: 23px; \r\n");
      out.write("\t\tfont-weight: bolder;\r\n");
      out.write("\t\tfont-style: normal;\r\n");
      out.write("\t\tfont-family: \"Lucida Console\", Monaco, monospace;\r\n");
      out.write("\t\tborder-radius: 7px;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.fncButton {\r\n");
      out.write("\t\tfloat: right;\r\n");
      out.write("\t\tmargin-top: 13px;\r\n");
      out.write("\t\tmargin-right: 50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.headerLine {\r\n");
      out.write("\t\tclear: both;\r\n");
      out.write("\t\tmargin-top: 50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.headerLine hr {\r\n");
      out.write("\t\tborder: solid 1.5px #ABABAB;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.productRegiBtn {\r\n");
      out.write("\t\tbackground-color: #DBDBDB; \r\n");
      out.write("\t\ttext-align: center; \r\n");
      out.write("\t\twidth:70px; \r\n");
      out.write("\t\theight: 25px;\r\n");
      out.write("\t\tcolor: #939393;\r\n");
      out.write("\t\tfont-size: 11px; \r\n");
      out.write("\t\tfont-weight: bolder;\r\n");
      out.write("\t\tfont-style: normal;\r\n");
      out.write("\t\tfont-family: \"Lucida Console\", Monaco, monospace;\r\n");
      out.write("\t\tborder-radius: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.myPageBtn {\r\n");
      out.write("\t\tbackground-color: #DBDBDB; \r\n");
      out.write("\t\ttext-align: center; \r\n");
      out.write("\t\twidth:70px; \r\n");
      out.write("\t\theight: 25px;\r\n");
      out.write("\t\tcolor: #939393;\r\n");
      out.write("\t\tfont-size: 11px; \r\n");
      out.write("\t\tfont-weight: bolder;\r\n");
      out.write("\t\tfont-style: normal;\r\n");
      out.write("\t\tfont-family: \"Lucida Console\", Monaco, monospace;\r\n");
      out.write("\t\tborder-radius: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.purchseListBtn {\r\n");
      out.write("\t\tbackground-color: #636363;\r\n");
      out.write("\t\ttext-align: center; \r\n");
      out.write("\t\twidth:70px; \r\n");
      out.write("\t\theight: 25px;\r\n");
      out.write("\t\tcolor: #FFFFFF;\r\n");
      out.write("\t\tfont-size: 11px; \r\n");
      out.write("\t\tfont-weight: bolder;\r\n");
      out.write("\t\tfont-style: normal;\r\n");
      out.write("\t\tfont-family: \"Lucida Console\", Monaco, monospace;\r\n");
      out.write("\t\tborder-radius: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.logoutBtn {\r\n");
      out.write("\t\tbackground-color: #636363;\r\n");
      out.write("\t\ttext-align: center; \r\n");
      out.write("\t\twidth:70px; \r\n");
      out.write("\t\theight: 25px;\r\n");
      out.write("\t\tcolor: #FFFFFF;\r\n");
      out.write("\t\tfont-size: 11px; \r\n");
      out.write("\t\tfont-weight: bolder;\r\n");
      out.write("\t\tfont-style: normal;\r\n");
      out.write("\t\tfont-family: \"Lucida Console\", Monaco, monospace;\r\n");
      out.write("\t\tborder-radius: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<title>JSP Homme</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"headerContainer\" >   \r\n");
      out.write("\r\n");
      out.write("\t<div class=\"shopName\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"JSP Homme\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"fncButton\">\t\r\n");
      out.write("\t\t<input class=\"productRegiBtn\" type=\"button\" value=\"제품등록\">\r\n");
      out.write("\t\t<input class=\"myPageBtn\" type=\"button\" value=\"마이페이지\">\r\n");
      out.write("\t\t<input class=\"purchseListBtn\" type=\"button\" value=\"구매목록\">\r\n");
      out.write("\t\t<input class=\"logoutBtn\" type=\"button\" value=\"로그아웃\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"headerLine\">\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
