/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-04-23 08:26:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#loginDiv {\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#loginH2 {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#loginTable {\r\n");
      out.write("\t\twidth: 400px;\r\n");
      out.write("\t\tmargin-left: 750px;\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttr {\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#loginRegiDiv {\r\n");
      out.write("\t\twidth: 400px;\r\n");
      out.write("\t\tmargin-left: 750px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t#loginBtn {\r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#memberRegiBtn{\r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#loginBodyDiv {\r\n");
      out.write("\t\twidth: 1920px;\r\n");
      out.write("\t\theight: 600px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<title>로그인</title>\r\n");
      out.write("\r\n");
      out.write("<!-- 아이디 validation 체크 어떻게 할꺼야? -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction loginFnc() {\r\n");
      out.write("\t\tvar idObj = document.getElementById(\"memberId\");\r\n");
      out.write("\t\tvar passwordObj = document.getElementById(\"memberPassword\");\r\n");
      out.write("\r\n");
      out.write("\t\tif (idObj.value == null || idObj.value == \"\") {\r\n");
      out.write("\t\t\talert(\"아이디를 입력해 주세요\");\r\n");
      out.write("\t\t\tidObj.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (passwordObj.value == null || passwordObj.value == \"\") {\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력해 주세요\")\r\n");
      out.write("\t\t\tpasswordObj.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar formObj = document.getElementById(\"loginForm\")\r\n");
      out.write("\t\tformObj.submit();\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction myRegisterFnc() {\r\n");
      out.write("\t\tlocation.href = \"../member/add.do\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/headerAfterLogin.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"loginBodyDiv\">\r\n");
      out.write("\r\n");
      out.write("\t<h2 id=\"loginH2\">사용자 로그인</h2>\r\n");
      out.write("\t<div id=\"loginDiv\">\r\n");
      out.write("\t\t<form action=\"loginCtr.do\" id=\"loginForm\" method=\"post\">\r\n");
      out.write("\t\t\t<table id=\"loginTable\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"font-weight:bolder; font-family: 'Lucida Console', Monaco, monospace;\">아이디</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"id\" id=\"memberId\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"font-weight:bolder; font-family: 'Lucida Console', Monaco, monospace;\">암호</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name='password' id=\"memberPassword\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\t\t\t\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<div id=\"loginRegiDiv\">\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"로그인\" id=\"loginBtn\" onclick=\"loginFnc();\">\r\n");
      out.write("\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"회원가입\" id=\"memberRegiBtn\" onclick=\"myRegisterFnc();\">\r\n");
      out.write("\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/tail.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
